# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZ-Z2o2nOyVdQbkXdtoORHTBqI1JgYji
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5])
y=np.array([0,100])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,6,8])
y=np.array([3,8,1,10])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,2,4,5,6,8,10,14,20,27])
y=np.array([1,15,2,20,3,19,10,10,10,10])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5,8,12])
y=np.array([0,6,10,16])
plt.plot(x,y, marker='*')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5,8,12])
y=np.array([0,6,10,16])
plt.plot(x,y, 'o--r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5,8,12])
y=np.array([0,6,10,16])
plt.plot(x,y, 'o--r',ms=15)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,5,8,12])
y=np.array([0,6,10,16])
plt.plot(x,y, 'o--r',ms=15,mec='b')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1=np.array([0,5,8,12])
y1=np.array([0,6,10,16])
x2=np.array([4,6,14,15])
y2=np.array([2,10,20,14])
plt.plot(x1,y1, 'o--r',ms=15)
plt.plot(x2,y2, '*:b',ms=10)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1=np.array([0,5,8,12])
y1=np.array([0,6,10,16])
x2=np.array([4,6,14,15])
y2=np.array([2,10,20,14])
plt.plot(x1,y1, 'o--r',ms=15,mfc='y')
plt.plot(x2,y2, '*:b',ms=10,mfc='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([5,6,8,6])
y=np.array([4,8,12,10])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,10,5,10,0])
y=np.array([0,0,7,14,14])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


import matplotlib.pyplot as plt
import numpy as np

x1=np.array([0,5,8,12])
y1=np.array([0,6,10,16])
x2=np.array([4,6,14,15])
y2=np.array([2,10,20,14])
plt.scatter(x1,y1, color='r')
plt.scatter(x2,y2, color='y')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,10,5,10,0])
y=np.array([0,0,7,14,14])
mycolor=['red','green','purple','lime','yellow']
plt.scatter(x,y,color=mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,10,5,10,0])
y=np.array([0,0,7,14,14])
mycolor=['red','green','purple','lime','yellow']
size=[100,20,35,45,60]
plt.scatter(x,y,color=mycolor,s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['A','B','C','D'])
y=np.array([3,8,5,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['A','B','C','D'])
y=np.array([3,8,5,10])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['A','B','C','D'])
y=np.array([3,8,5,10])
plt.bar(x,y,width=0.1)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])

plt.pie(x)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]

plt.pie(x,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]

plt.pie(x,labels=mylabels,startangle=90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode,shadow=True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]
mycolors=["black","hotpink","b","#4CAF50"]
myexplode=[0.2,0,0,0]
plt.pie(x,labels=mylabels,startangle=90,explode=myexplode, colors=mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]

plt.pie(x,labels=mylabels)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([10,30,25,35])
mylabels=["Ananas","Banan","Apple","Dates"]

plt.pie(x,labels=mylabels)
plt.legend(title='Four Fruits')
plt.show()